<?php

$page_title = "Play Quiz";
$page_header = "Welcome to Quiz Program";

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $page_title ?></title>
    <link rel="stylesheet" href="styles.css">
    <a href="login.php">Login</a>
	<a href="register.PHP">Register</a>
</head>
<body>
	<h2><?php echo $page_header ?></h2>
	<a href="login.PHP">Login</a>
	<a href="register.PHP">Register</a>
</body>
</html>